#!/usr/bin/env bash
# Quick start for Skillforge
# This script demonstrates how to use Skillforge

echo "🚀 Skillforge Quick Start"
echo ""
echo "Option 1: Install globally"
echo "  npm install -g @abhinavdobhal/skillforge"
echo "  skillforge init --ai claude"
echo ""
echo "Option 2: Use with npx"
echo "  npx @abhinavdobhal/skillforge init --ai cursor"
echo ""
echo "Option 3: Local development"
echo "  node bin/skillforge.js init --ai windsurf"
echo ""
echo "Supported IDEs:"
echo "  - claude (Claude Code)"
echo "  - cursor (Cursor Editor)"
echo "  - windsurf (Windsurf)"
echo "  - antigravity (Antigravity)"
echo "  - copilot (GitHub Copilot)"
echo "  - kiro (Kiro)"
echo "  - codex (Codex CLI)"
echo ""
echo "View generated project:"
echo "  cat .agent/ARCHITECTURE.md"
echo "  ls .agent/agents/       # View all agents"
echo "  ls .agent/skills/       # View all skills"
echo "  ls .agent/workflows/    # View all workflows"
